package tqs.midterm.project;// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class SearchByCoordsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/home/alexis/Downloads/chromedriver_linux64/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchByCoords() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1294, 741));
    driver.findElement(By.id("latitude")).sendKeys("40.763841");
    driver.findElement(By.id("latitude")).click();
    driver.findElement(By.id("longitude")).click();
    driver.findElement(By.id("longitude")).sendKeys("-73.972972");
    driver.findElement(By.cssSelector(".submit-btn")).click();
    assertThat(driver.findElement(By.xpath("//h2")).getText(), is("Manhattan, United States"));
    assertThat(driver.findElement(By.cssSelector(".coordinates")).getText(), is("(40.763841, -73.972972)"));
  }
}
